### PR TITLE
fix: :bug: local repos not getting updated

### LINKED ISSUE #4: Synced repo not updated with latest changes
### Describe the Bug

I've been using git-sync for some days now and I went on to check whether the backups were working... And after a `git log`, I actually noticed the repos were outdated and just had commits from the day I cloned them.
At first I thought the issues were my cronbjos, but after running git-sync manually, I noticed that even though it says it's updating the repos (and it might really do that), that change is not reflected locally, when I `git log` those repos.
I don't know for sure if the `fetch` command git-sync does is actually getting any changes, but I tried to run the same command in my machine (`git -C repoPath fetch --all`) and noticed the same behaviour. The fetch works successfully, but it doesn't bring any changes I have in my GitHub repos in a way that I can verify them with `git log`.

### Steps to reproduce

1. Do a first git-sync, cloning repos.
2. Work on those repos and push changes to GitHub.
3. Do another git-sync.
4. Even if it's successful, you won't see any of the changes reflected.

### Relevant log output

_No response_

### Which browser are you using? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jbonadiman**
Even after a successful sync and a report of "Updated repo", if a "git log" was performed in a cloned repo, it wouldn't show the updates of the remote. Explicitly giving fetch the remote name, makes it show the local commit history correctly.

This could fix #4.

Edit: I've based this change off this StackOverflow discussion/answer: https://stackoverflow.com/a/3382703

### CODE REVIEW

File: pkg/sync/sync.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func CloneOrUpdateRepo(repo *github.Repository, backupDir string, config config.
 		}
 	} else {
 		log.Default().Println("Updating repo:", repo.GetName())
-		if _, err := exec.Command("git", "-C", repoPath, "fetch", "--all").Output(); err != nil {
+		if _, err := exec.Command("git", "-C", repoPath, "fetch", "origin", "*:*").Output(); err != nil {
```
Comment (AkashRajpurohit) [inline pkg/sync/sync.go:65]: Does this work though? I am seeing errors when it tries to update the repo 🤔

Comment (jbonadiman) [reply pkg/sync/sync.go:65]: I compiled the program, tested it, and it worked. What kind of errors are you having?

Comment (AkashRajpurohit) [reply pkg/sync/sync.go:65]: It failed with exit status 1 for me when I tested for few repositories, I am also looking into the fix for it, thanks for reporting this!

**Comment by AkashRajpurohit** [comment]
Weird but this fix consistently works for me, but issuing git command directly does not work 🤔

**Comment by jbonadiman** [comment]
Yeah that's really weird.
I've just read your commit, didn't test it, but I'd right away suggest using %q instead of %s, so that the formatting automatically adds quotes and it prevents path issues (like spaces).

**Comment by jbonadiman** [comment]
I tested your commit and this is still working for me, but I really needed to replace the `%s` for `%q`.
I noticed that the git command is basically the same and the main change in your commit is that you're "wrapping" the command in a `sh -c` call. Doesn't that basically makes the executable not run properly in Windows anymore? What is that really fixing compared to the direct git call?
I actually run Windows and the executable just happened to run in my machine because I installed git with scoop and scoop automatically creates a shortcut for `sh`, but I don't think that's the default when you install git manually (although it does come with a Linux shell).
Is there maybe another fix that wouldn't involve the `sh` call? 🤔

**Comment by AkashRajpurohit** [comment]
I will be looking into this today, but yes we need to ensure that it does not break on other OS, I am testing heavily on Mac so Unix based system for now. Feel free to update this PR if you see any viable fix, I will contribute to the same. Thanks.

File: pkg/sync/sync.go (hunk 1 above)
Comment (AkashRajpurohit) [reply pkg/sync/sync.go]: I think I found the reason why there was exit status 1 when I was testing it, basically the command you mentioned for fetch origin "*:*" is perfect, how it's being used was probably the reason for error, I am pushing a commit which should fix it, so give it a try once post that.

**Comment by AkashRajpurohit** [comment]
This one seems to fix the issue for all cases which I have tested, it should be good to merge and released. Thanks for pointing this out and sharing the fix!

**Comment by AkashRajpurohit** [comment]
@all-contributors please add @jbonadiman for code and ideas.
